### ISSUE TITLE
Tiles

### ISSUE THREAD

**Issue by Joonsey** [Joonsey/ngn#1]
## Versatile tile system

We want to have a lifecycle for the tiles, that means a create, update, render and free for tiles.

We know that tiles are contained within **rooms** and that they should be created upon creation of a **room**.

For now the tile is very simple and is a struct purely consisting of TileType:
```c
typedef struct Tile {
	TileType type;
} Tile;
```

We may need to store the position of the tile, to check for collision. We can also infer from the TileType whether or not the tile has collisions or we can store it on the tile.

Alternatively we can store more of this data on the Entity struct and revolve more around a entity system.
```c
typedef struct Entity {
	Vector2 position;
	Texture2D texture; 
	Texture UV_texture;
        bool can_collide;
} Entity;

typedef struct Tile {
	TileType type;
	Entity e;
} Tile;
```

This should be stored in it's own file named tile.c / tile.h. similar to the room.h / *.c

Up to you though!

**Comment by Joonsey** [comment]
added in this commit 8fed0f3d5178dec131a0ca06edbeb459d918e5f8

**Comment by TacosIsDank** [comment]
🙏🥳🥳🥳
